### ISSUE TITLE
google-cloud-texttospeech update broken

### ISSUE THREAD

**Issue by jbt2000** [yoonghm/AnnotatePptx#1]
The latest revision of google-cloud-texttospeech breaks AnnotatePptx.
- enums and types were removed - removing enums. and types. from the script fix the issue
- positional parameters error in synthesize_speech ... it relates to this article, but the codes used here differ too much from the example  for me to fix - please help:
https://googleapis.dev/python/texttospeech/latest/UPGRADING.html

Many thanks

**Comment by RobWalker** [comment]
Changing line 69 to:

```
        response = self.__client.synthesize_speech(
            input=input,
            voice=self.__voice,
            audio_config=self.__audio_config
        )
```

worked for me

**Comment by rangervaloy** [comment]
[AnnotatePptx.py.docx](https://github.com/yoonghm/AnnotatePptx/files/13421090/AnnotatePptx.py.docx)

Attached is the fully fixed script (remove extension .docx)

**Comment by yoonghm** [comment]
Thank yo all. I have updated code based on your valuable suggestion. I have also fixed another bug on the
```
else:
    sex = 'neutral'
```
